name: job-matcher-api
services:
- name: web
  source_dir: /
  github:
    repo: your-username/job-matcher-flask
    branch: main
  run_command: gunicorn --bind 0.0.0.0:$PORT app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
  - key: PORT
    value: "8080"
  - key: ALLOWED_ORIGINS
    value: "https://app.lovable.dev,https://app.lovable.co"
  http_port: 8080
  routes:
  - path: /
